### ISSUE TITLE
Blender 3.0 compatibility?

### ISSUE THREAD

**Issue by yxx10** [franMarz/TexTools-Blender#119]
Hi, I recently updated Blender to the latest version (3.0) and when I tried baking, this error appeared on the console:

> Python: Traceback (most recent call last):
  File "C:\Users\[blah blah blah]\TexTools_1_4_4\op_bake.py", line 152, in execute
    ub.store_bake_settings()
  File "C:\Users\[blah blah blah]\TexTools_1_4_4\utilities_bake.py", line 73, in store_bake_settings
    settings.use_progressive_refine = bpy.context.scene.cycles.use_progressive_refine
AttributeError: 'CyclesRenderSettings' object has no attribute 'use_progressive_refine'
location: <unknown location>:-1

Is this a compatibility issue? or do I need to reconfigure something to make the addon work? Thanks!

**Comment by ghost** [comment]
I'm also having this issue. I guess it's because Cycles no longer has that feature?

**Comment by yxx10** [comment]
> I'm also having this issue. I guess it's because Cycles no longer has that feature?

Seems like the most obvious answer. Apparently they're already working on TexTools 1.5, I suppose this will get solved on that version.

**Comment by franMarz** [comment]
Please always [download and install the latest version (from the main branch)](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) before posting an issue here. That was solved a long time ago.
