### ISSUE TITLE
Blender 3.0 adaptation?

### ISSUE THREAD

**Issue by gerroon** [franMarz/TexTools-Blender#101]
Hi

it seems like baking does not work with the current 3.0 builds.

I am using 1.4.4 on Windows 10 

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\textools\op_bake.py", line 152, in execute
    ub.store_bake_settings()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\textools\utilities_bake.py", line 73, in store_bake_settings
    settings.use_progressive_refine = bpy.context.scene.cycles.use_progressive_refine
AttributeError: 'CyclesRenderSettings' object has no attribute 'use_progressive_refine'

location: <unknown location>:-1

```

**Comment by franMarz** [comment]
[https://github.com/SavMartin/TexTools-Blender/projects](https://github.com/SavMartin/TexTools-Blender/projects)
